version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: board_db
      MYSQL_USER: boarduser
      MYSQL_PASSWORD: boardpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: ./app
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code
    environment:
      DB_HOST: db
      DB_NAME: board_db
      DB_USER: boarduser
      DB_PASS: boardpass
      PYTHONPATH: /code

volumes:
  db_data:
